from app.schemas.funds import FundDetail, NavPoint

DATA_UPDATED_AT = "2026-07-08T20:30:00+08:00"

FUNDS: list[FundDetail] = [
    FundDetail(
        code="000001",
        name="稳健成长混合 A",
        fund_type="mixed",
        risk_level="R3",
        manager_name="陈安",
        inception_date="2018-03-15",
        fund_size_billion=42.6,
        management_fee=1.2,
        custody_fee=0.2,
        annualized_return_3y=8.4,
        annualized_return_5y=9.1,
        max_drawdown=-16.8,
        sharpe_ratio=1.38,
        category_rank_percentile=18,
        manager_years=8,
        source="sample_local",
        data_updated_at=DATA_UPDATED_AT,
        navs=[
            NavPoint(trade_date="2021", nav=1.02, accumulated_nav=1.02),
            NavPoint(trade_date="2022", nav=1.08, accumulated_nav=1.08),
            NavPoint(trade_date="2023", nav=1.16, accumulated_nav=1.16),
            NavPoint(trade_date="2024", nav=1.24, accumulated_nav=1.24),
            NavPoint(trade_date="2025", nav=1.31, accumulated_nav=1.31),
            NavPoint(trade_date="2026", nav=1.38, accumulated_nav=1.38),
        ],
        ai_summary="收益和回撤处于同类较优区间，风险等级 R3，适合 C3 及以上用户进一步研究。",
    ),
    FundDetail(
        code="000002",
        name="均衡配置债券 A",
        fund_type="bond",
        risk_level="R2",
        manager_name="李宁",
        inception_date="2017-06-01",
        fund_size_billion=86.2,
        management_fee=0.6,
        custody_fee=0.15,
        annualized_return_3y=4.6,
        annualized_return_5y=5.0,
        max_drawdown=-5.2,
        sharpe_ratio=1.62,
        category_rank_percentile=22,
        manager_years=11,
        source="sample_local",
        data_updated_at=DATA_UPDATED_AT,
        navs=[
            NavPoint(trade_date="2021", nav=1.01, accumulated_nav=1.01),
            NavPoint(trade_date="2022", nav=1.04, accumulated_nav=1.04),
            NavPoint(trade_date="2023", nav=1.09, accumulated_nav=1.09),
            NavPoint(trade_date="2024", nav=1.13, accumulated_nav=1.13),
            NavPoint(trade_date="2025", nav=1.17, accumulated_nav=1.17),
            NavPoint(trade_date="2026", nav=1.21, accumulated_nav=1.21),
        ],
        ai_summary="波动较低、费用较低，适合作为稳健型或保守型组合的底仓候选。",
    ),
    FundDetail(
        code="000003",
        name="红利低波指数增强",
        fund_type="stock",
        risk_level="R3",
        manager_name="王澄",
        inception_date="2019-09-20",
        fund_size_billion=31.4,
        management_fee=1.0,
        custody_fee=0.18,
        annualized_return_3y=7.8,
        annualized_return_5y=8.5,
        max_drawdown=-18.4,
        sharpe_ratio=1.25,
        category_rank_percentile=28,
        manager_years=6,
        source="sample_local",
        data_updated_at=DATA_UPDATED_AT,
        navs=[
            NavPoint(trade_date="2021", nav=1.0, accumulated_nav=1.0),
            NavPoint(trade_date="2022", nav=1.03, accumulated_nav=1.03),
            NavPoint(trade_date="2023", nav=1.12, accumulated_nav=1.12),
            NavPoint(trade_date="2024", nav=1.18, accumulated_nav=1.18),
            NavPoint(trade_date="2025", nav=1.26, accumulated_nav=1.26),
            NavPoint(trade_date="2026", nav=1.34, accumulated_nav=1.34),
        ],
        ai_summary="红利低波策略降低了部分权益波动，但仍属于权益类风险暴露，需要结合组合比例查看。",
    ),
    FundDetail(
        code="000004",
        name="短债现金增强",
        fund_type="bond",
        risk_level="R1",
        manager_name="赵瑜",
        inception_date="2020-02-10",
        fund_size_billion=66.0,
        management_fee=0.3,
        custody_fee=0.08,
        annualized_return_3y=2.8,
        annualized_return_5y=3.0,
        max_drawdown=-1.8,
        sharpe_ratio=1.44,
        category_rank_percentile=24,
        manager_years=9,
        source="sample_local",
        data_updated_at=DATA_UPDATED_AT,
        navs=[
            NavPoint(trade_date="2021", nav=1.0, accumulated_nav=1.0),
            NavPoint(trade_date="2022", nav=1.02, accumulated_nav=1.02),
            NavPoint(trade_date="2023", nav=1.05, accumulated_nav=1.05),
            NavPoint(trade_date="2024", nav=1.07, accumulated_nav=1.07),
            NavPoint(trade_date="2025", nav=1.1, accumulated_nav=1.1),
            NavPoint(trade_date="2026", nav=1.12, accumulated_nav=1.12),
        ],
        ai_summary="低波动短债样本，适合作为闲钱管理学习场景的现金替代观察对象。",
    ),
]
